export default exercisesMap = {
  back: [
    "alternate lateral pulldown",
    "archer pull up",
    "assisted parallel close grip pull-up",
    "assisted pull-up",
    "assisted standing chin-up",
    "assisted standing pull-up",
    "back extension on exercise ball",
    "back lever",
    "back pec stretch",
    "band assisted pull-up",
    "band close-grip pulldown",
    "band fixed back close grip pulldown",
    "band fixed back underhand pulldown",
    "band kneeling one arm pulldown",
    "band one arm standing low row",
    "band one arm twisting seated row",
    "band shrug",
    "band straight leg deadlift",
    "band underhand pulldown",
    "barbell bent arm pullover",
    "barbell bent over row",
    "barbell decline bent arm pullover",
    "barbell decline wide-grip pullover",
    "barbell incline row",
    "barbell one arm bent over row",
    "barbell pendlay row",
    "barbell pullover",
    "barbell pullover to press",
    "barbell reverse grip bent over row",
    "barbell reverse grip incline bench row",
    "barbell shrug",
    "bench pull-ups",
    "bodyweight squatting row",
    "bodyweight squatting row (with towel)",
    "bodyweight standing close-grip one arm row",
    "bodyweight standing close-grip row",
    "bodyweight standing one arm row",
    "bodyweight standing one arm row (with towel)",
    "bodyweight standing row",
    "bodyweight standing row (with towel)",
    "cable bar lateral pulldown",
    "cable cross-over lateral pulldown",
    "cable decline seated wide-grip row",
    "cable floor seated wide-grip row",
    "cable high row (kneeling)",
    "cable incline bench row",
    "cable incline pushdown",
    "cable lat pulldown full range of motion",
    "cable lateral pulldown (with rope attachment)",
    "cable lateral pulldown with v-bar",
    "cable low seated row",
    "cable lying extension pullover (with rope attachment)",
    "cable one arm bent over row",
    "cable one arm pulldown",
    "cable one arm straight back high row (kneeling)",
    "cable palm rotational row",
    "cable pulldown",
    "cable pulldown (pro lat bar)",
    "cable pushdown (straight arm) v. 2",
    "cable rear pulldown",
    "cable reverse-grip straight back seated high row",
    "cable rope crossover seated row",
    "cable rope elevated seated row",
    "cable rope extension incline bench row",
    "cable rope seated row",
    "cable seated high row (v-bar)",
    "cable seated one arm alternate row",
    "cable seated row",
    "cable seated wide-grip row",
    "cable shrug",
    "cable squat row (with rope attachment)",
    "cable standing row (v-bar)",
    "cable standing twist row (v-bar)",
    "cable straight arm pulldown",
    "cable straight arm pulldown (with rope)",
    "cable straight back seated row",
    "cable thibaudeau kayak row",
    "cable twisting pull",
    "cable underhand pulldown",
    "cable upper row",
    "cable wide grip rear pulldown behind neck",
    "cambered bar lying row",
    "chin-up",
    "chin-ups (narrow parallel grip)",
    "close grip chin-up",
    "dumbbell bent over row",
    "dumbbell decline shrug",
    "dumbbell decline shrug v. 2",
    "dumbbell incline row",
    "dumbbell incline shrug",
    "dumbbell incline y-raise",
    "dumbbell lying rear delt row",
    "dumbbell one arm bent-over row",
    "dumbbell palm rotational bent over row",
    "dumbbell reverse grip incline bench one arm row",
    "dumbbell reverse grip incline bench two arm row",
    "dumbbell reverse grip row (female)",
    "dumbbell shrug",
    "dumbbell side plank with rear fly",
    "elbow lift - reverse push-up",
    "elevator",
    "exercise ball alternating arm ups",
    "exercise ball back extension with arms extended",
    "exercise ball back extension with hands behind head",
    "exercise ball back extension with knees off ground",
    "exercise ball back extension with rotation",
    "exercise ball hug",
    "exercise ball lat stretch",
    "exercise ball lower back stretch (pyramid)",
    "exercise ball lying side lat stretch",
    "exercise ball prone leg raise",
    "ez bar lying bent arms pullover",
    "ez bar reverse grip bent over row",
    "front lever reps",
    "gironda sternum chin",
    "hyperextension",
    "hyperextension (on bench)",
    "inverted row",
    "inverted row bent knees",
    "inverted row on bench",
    "inverted row v. 2",
    "inverted row with straps",
    "kettlebell alternating renegade row",
    "kettlebell alternating row",
    "kettlebell one arm row",
    "kettlebell sumo high pull",
    "kettlebell two arm row",
    "kipping muscle up",
    "kneeling lat stretch",
    "l-pull-up",
    "lever alternating narrow grip seated row ",
    "lever assisted chin-up",
    "lever back extension",
    "lever bent over row ",
    "lever bent-over row with v-bar ",
    "lever front pulldown",
    "lever gripless shrug",
    "lever gripless shrug v. 2",
    "lever high row ",
    "lever narrow grip seated row ",
    "lever one arm bent over row ",
    "lever one arm lateral high row",
    "lever one arm lateral wide pulldown ",
    "lever pullover ",
    "lever reverse grip lateral pulldown ",
    "lever reverse grip vertical row",
    "lever reverse t-bar row",
    "lever seated row",
    "lever shrug ",
    "lever t bar row ",
    "lever t-bar reverse grip row",
    "lever unilateral row",
    "london bridge",
    "lower back curl",
    "medicine ball catch and overhead throw",
    "medicine ball overhead slam",
    "mixed grip chin-up",
    "muscle up",
    "muscle-up (on vertical bar)",
    "one arm against wall",
    "one arm chin-up",
    "one arm towel row",
    "pull up (neutral grip)",
    "pull-up",
    "rear pull-up",
    "resistance band seated straight back row",
    "reverse grip machine lat pulldown",
    "reverse grip pull-up",
    "rocky pull-up pulldown",
    "roller back stretch",
    "roller side lat stretch",
    "rope climb",
    "scapula dips",
    "scapular pull-up",
    "seated lower back stretch",
    "shoulder grip pull-up",
    "side lying floor stretch",
    "side-to-side chin",
    "skin the cat",
    "smith back shrug",
    "smith bent over row",
    "smith narrow row",
    "smith one arm row",
    "smith reverse grip bent over row",
    "smith shrug",
    "sphinx",
    "spine stretch",
    "standing archer",
    "standing lateral stretch",
    "standing pelvic tilt",
    "suspended row",
    "twin handle parallel grip lat pulldown",
    "two toe touch (male)",
    "upper back stretch",
    "upward facing dog",
    "weighted close grip chin-up on dip cage",
    "weighted hyperextension (on stability ball)",
    "weighted muscle up",
    "weighted muscle up (on bar)",
    "weighted one hand pull up",
    "weighted pull-up",
    "wide grip pull-up",
    "wide grip rear pull-up",
  ],
  cardio: [
    "astride jumps (male)",
    "back and forth step",
    "bear crawl",
    "burpee",
    "cycle cross trainer",
    "dumbbell burpee",
    "half knee bends (male)",
    "high knee against wall",
    "jack burpee",
    "jack jump (male)",
    "jump rope",
    "mountain climber",
    "push to run",
    "run",
    "run (equipment)",
    "scissor jumps (male)",
    "semi squat jump (male)",
    "short stride run",
    "skater hops",
    "ski step",
    "star jump (male)",
    "stationary bike run v. 3",
    "stationary bike walk",
    "swing 360",
    "walk elliptical cross trainer",
    "walking high knees lunge",
    "walking on incline treadmill",
    "walking on stepmill",
    "wheel run",
  ],
  chest: [
    "archer push up",
    "assisted chest dip (kneeling)",
    "assisted seated pectoralis major stretch with stability ball",
    "assisted wide-grip chest dip (kneeling)",
    "band bench press",
    "band one arm twisting chest press",
    "barbell bench press",
    "barbell decline bench press",
    "barbell decline pullover",
    "barbell decline wide-grip press",
    "barbell front raise and pullover",
    "barbell guillotine bench press",
    "barbell incline bench press",
    "barbell incline shoulder raise",
    "barbell reverse grip decline bench press",
    "barbell reverse grip incline bench press",
    "barbell wide bench press",
    "barbell wide reverse grip bench press",
    "behind head chest stretch",
    "cable bench press",
    "cable cross-over variation",
    "cable decline fly",
    "cable decline one arm press",
    "cable decline press",
    "cable incline bench press",
    "cable incline fly",
    "cable incline fly (on stability ball)",
    "cable low fly",
    "cable lying fly",
    "cable middle fly",
    "cable one arm decline chest fly",
    "cable one arm fly on exercise ball",
    "cable one arm incline fly on exercise ball",
    "cable one arm incline press",
    "cable one arm incline press on exercise ball",
    "cable one arm lateral bent-over",
    "cable one arm press on exercise ball",
    "cable press on exercise ball",
    "cable seated chest press",
    "cable standing fly",
    "cable standing up straight crossovers",
    "cable upper chest crossovers",
    "chest and front of shoulder stretch",
    "chest dip",
    "chest dip (on dip-pull-up cage)",
    "chest dip on straight bar",
    "chest stretch with exercise ball",
    "chest tap push-up (male)",
    "clap push up",
    "clock push-up",
    "decline push-up",
    "deep push up",
    "drop push up",
    "dumbbell around pullover",
    "dumbbell bench press",
    "dumbbell decline bench press",
    "dumbbell decline fly",
    "dumbbell decline hammer press",
    "dumbbell decline one arm fly",
    "dumbbell decline twist fly",
    "dumbbell fly",
    "dumbbell fly on exercise ball",
    "dumbbell incline alternate press",
    "dumbbell incline bench press",
    "dumbbell incline breeding",
    "dumbbell incline fly",
    "dumbbell incline fly on exercise ball",
    "dumbbell incline hammer press",
    "dumbbell incline one arm fly",
    "dumbbell incline one arm fly on exercise ball",
    "dumbbell incline one arm press",
    "dumbbell incline one arm press on exercise ball",
    "dumbbell incline palm-in press",
    "dumbbell incline press on exercise ball",
    "dumbbell incline shoulder raise",
    "dumbbell incline twisted flyes",
    "dumbbell lying hammer press",
    "dumbbell lying one arm press",
    "dumbbell lying one arm press v. 2",
    "dumbbell lying pullover on exercise ball",
    "dumbbell one arm bench fly",
    "dumbbell one arm chest fly on exercise ball",
    "dumbbell one arm decline chest press",
    "dumbbell one arm fly on exercise ball",
    "dumbbell one arm incline chest press",
    "dumbbell one arm press on exercise ball",
    "dumbbell one arm pullover on exercise ball",
    "dumbbell one arm reverse grip press",
    "dumbbell one leg fly on exercise ball",
    "dumbbell press on exercise ball",
    "dumbbell pullover",
    "dumbbell pullover hip extension on exercise ball",
    "dumbbell pullover on exercise ball",
    "dumbbell reverse bench press",
    "dumbbell straight arm pullover",
    "dynamic chest stretch (male)",
    "exercise ball pike push up",
    "floor fly (with barbell)",
    "full planche push-up",
    "hands bike",
    "hyght dumbbell fly",
    "incline push up depth jump",
    "incline push-up",
    "incline push-up (on box)",
    "incline reverse grip push-up",
    "incline scapula push up",
    "isometric chest squeeze",
    "isometric wipers",
    "kettlebell alternating press on floor",
    "kettlebell extended range one arm press on floor",
    "kettlebell one arm floor press",
    "kettlebell plyo push-up",
    "kneeling push-up (male)",
    "korean dips",
    "lever chest press",
    "lever chest press ",
    "lever chest press v. 2",
    "lever decline chest press",
    "lever incline chest press",
    "lever incline chest press v. 2",
    "lever seated fly",
    "lever standing chest press",
    "machine inner chest press",
    "medicine ball chest pass",
    "medicine ball chest push from 3 point stance",
    "medicine ball chest push multiple response",
    "medicine ball chest push single response",
    "medicine ball chest push with run release",
    "modified hindu push-up (male)",
    "plyo push up",
    "push and pull bodyweight",
    "push up on bosu ball",
    "push-up",
    "push-up (bosu ball)",
    "push-up (on stability ball)",
    "push-up (wall)",
    "push-up (wall) v. 2",
    "push-up medicine ball",
    "push-up plus",
    "raise single arm push-up",
    "resistance band seated chest press",
    "roller seated shoulder flexor depresor retractor",
    "roller seated single leg shoulder flexor depresor retractor",
    "scapula push-up",
    "shoulder tap push-up",
    "single arm push-up",
    "smith bench press",
    "smith decline bench press",
    "smith decline reverse-grip press",
    "smith incline bench press",
    "smith incline reverse-grip press",
    "smith incline shoulder raises",
    "smith machine reverse decline close grip bench press",
    "smith reverse-grip press",
    "smith wide grip bench press",
    "smith wide grip decline bench press",
    "superman push-up",
    "suspended push-up",
    "weighted drop push up",
    "weighted straight bar dip",
    "weighted svend press",
    "wide hand push up",
    "wide-grip chest dip on high parallel bars",
  ],
  "lower arms": [
    "band reverse wrist curl",
    "band wrist curl",
    "barbell palms down wrist curl over a bench",
    "barbell palms up wrist curl over a bench",
    "barbell revers wrist curl v. 2",
    "barbell reverse wrist curl",
    "barbell standing back wrist curl",
    "barbell wrist curl",
    "barbell wrist curl v. 2",
    "cable reverse wrist curl",
    "cable standing back wrist curl",
    "cable wrist curl",
    "dumbbell finger curls",
    "dumbbell lying pronation",
    "dumbbell lying pronation on floor",
    "dumbbell lying supination",
    "dumbbell lying supination on floor",
    "dumbbell one arm revers wrist curl",
    "dumbbell one arm seated neutral wrist curl",
    "dumbbell one arm wrist curl",
    "dumbbell over bench one arm reverse wrist curl",
    "dumbbell over bench one arm wrist curl",
    "dumbbell over bench revers wrist curl",
    "dumbbell over bench wrist curl",
    "dumbbell reverse wrist curl",
    "dumbbell seated one arm rotate",
    "dumbbell seated palms up wrist curl",
    "finger curls",
    "kettlebell alternating hang clean",
    "lever gripper hands ",
    "modified push up to lower arms",
    "side wrist pull stretch",
    "smith seated wrist curl",
    "smith standing back wrist curl",
    "weighted standing hand squeeze",
    "wrist circles",
    "wrist rollerer",
  ],
  "lower legs": [
    "ankle circles",
    "assisted lying calves stretch",
    "band single leg calf raise",
    "band single leg reverse calf raise",
    "band two legs calf raise - (band under both legs) v. 2",
    "barbell floor calf raise",
    "barbell seated calf raise",
    "barbell standing calf raise",
    "barbell standing leg calf raise",
    "barbell standing rocking leg calf raise",
    "bodyweight standing calf raise",
    "box jump down with one leg stabilization",
    "cable standing calf raise",
    "cable standing one leg calf raise",
    "calf push stretch with hands against wall",
    "calf stretch with hands against wall",
    "calf stretch with rope",
    "circles knee stretch",
    "donkey calf raise",
    "dumbbell seated calf raise",
    "dumbbell seated one leg calf raise",
    "dumbbell seated one leg calf raise - hammer grip",
    "dumbbell seated one leg calf raise - palm up",
    "dumbbell single leg calf raise",
    "dumbbell standing calf raise",
    "exercise ball on the wall calf raise",
    "exercise ball on the wall calf raise (tennis ball between ankles)",
    "exercise ball on the wall calf raise (tennis ball between knees)",
    "hack calf raise",
    "hack one leg calf raise",
    "lever calf press ",
    "lever donkey calf raise",
    "lever rotary calf",
    "lever seated calf press",
    "lever seated calf raise ",
    "lever seated squat calf raise on leg press machine",
    "lever standing calf raise",
    "one leg donkey calf raise",
    "one leg floor calf raise",
    "peroneals stretch",
    "posterior tibialis stretch",
    "seated calf stretch (male)",
    "single leg calf raise (on a dumbbell)",
    "sled 45в° calf press",
    "sled calf press on leg press",
    "sled forward angled calf raise",
    "sled lying calf press",
    "sled one leg calf press on leg press",
    "smith one leg floor calf raise",
    "smith reverse calf raises",
    "smith seated one leg calf raise",
    "smith standing leg calf raise",
    "smith toe raise",
    "standing calf raise (on a staircase)",
    "standing calves",
    "standing calves calf stretch",
    "weighted donkey calf raise",
  ],
  neck: ["neck side stretch", "side push neck stretch"],
  shoulders: [
    "band front lateral raise",
    "band front raise",
    "band reverse fly",
    "band shoulder press",
    "band standing rear delt row",
    "band twisting overhead press",
    "band y-raise",
    "barbell front raise",
    "barbell one arm snatch",
    "barbell rear delt raise",
    "barbell rear delt row",
    "barbell seated behind head military press",
    "barbell seated bradford rocky press",
    "barbell seated overhead press",
    "barbell skier",
    "barbell standing bradford press",
    "barbell standing close grip military press",
    "barbell standing front raise over head",
    "barbell standing wide military press",
    "barbell thruster",
    "barbell upright row",
    "barbell upright row v. 2",
    "barbell upright row v. 3",
    "barbell wide-grip upright row",
    "battling ropes",
    "cable alternate shoulder press",
    "cable cross-over revers fly",
    "cable forward raise",
    "cable front raise",
    "cable front shoulder raise",
    "cable kneeling rear delt row (with rope) (male)",
    "cable lateral raise",
    "cable one arm lateral raise",
    "cable rear delt row (stirrups)",
    "cable rear delt row (with rope)",
    "cable seated rear lateral raise",
    "cable seated shoulder internal rotation",
    "cable shoulder press",
    "cable standing cross-over high reverse fly",
    "cable standing rear delt row (with rope)",
    "cable standing shoulder external rotation",
    "cable supine reverse fly",
    "cable upright row",
    "dumbbell alternate side press",
    "dumbbell arnold press",
    "dumbbell arnold press v. 2",
    "dumbbell bench seated press",
    "dumbbell cuban press",
    "dumbbell cuban press v. 2",
    "dumbbell front raise",
    "dumbbell front raise v. 2",
    "dumbbell full can lateral raise",
    "dumbbell incline one arm lateral raise",
    "dumbbell incline raise",
    "dumbbell incline rear lateral raise",
    "dumbbell incline t-raise",
    "dumbbell iron cross",
    "dumbbell lateral raise",
    "dumbbell lateral to front raise",
    "dumbbell lying external shoulder rotation",
    "dumbbell lying on floor rear delt raise",
    "dumbbell lying one arm deltoid rear",
    "dumbbell lying one arm rear lateral raise",
    "dumbbell lying rear lateral raise",
    "dumbbell one arm lateral raise",
    "dumbbell one arm lateral raise with support",
    "dumbbell one arm reverse fly (with support)",
    "dumbbell one arm shoulder press",
    "dumbbell one arm shoulder press v. 2",
    "dumbbell one arm upright row",
    "dumbbell push press",
    "dumbbell raise",
    "dumbbell rear delt raise",
    "dumbbell rear delt row_shoulder",
    "dumbbell rear fly",
    "dumbbell rear lateral raise",
    "dumbbell rear lateral raise (support head)",
    "dumbbell reverse fly",
    "dumbbell rotation reverse fly",
    "dumbbell scott press",
    "dumbbell seated alternate front raise",
    "dumbbell seated alternate press",
    "dumbbell seated alternate shoulder",
    "dumbbell seated bent arm lateral raise",
    "dumbbell seated front raise",
    "dumbbell seated lateral raise",
    "dumbbell seated lateral raise v. 2",
    "dumbbell seated shoulder press",
    "dumbbell seated shoulder press (parallel grip)",
    "dumbbell side lying one hand raise",
    "dumbbell single arm overhead carry",
    "dumbbell standing alternate overhead press",
    "dumbbell standing alternate raise",
    "dumbbell standing around world",
    "dumbbell standing front raise above head",
    "dumbbell standing one arm palm in press",
    "dumbbell standing overhead press",
    "dumbbell standing palms in press",
    "dumbbell upright row",
    "dumbbell upright row (back pov)",
    "dumbbell upright shoulder external rotation",
    "dumbbell w-press",
    "ez barbell anti gravity press",
    "kettlebell alternating press",
    "kettlebell arnold press",
    "kettlebell double jerk",
    "kettlebell double push press",
    "kettlebell double snatch",
    "kettlebell one arm clean and jerk",
    "kettlebell one arm jerk",
    "kettlebell one arm military press to the side",
    "kettlebell one arm push press",
    "kettlebell one arm snatch",
    "kettlebell pirate supper legs",
    "kettlebell seated press",
    "kettlebell seated two arm military press",
    "kettlebell seesaw press",
    "kettlebell thruster",
    "kettlebell two arm clean",
    "kettlebell two arm military press",
    "landmine lateral raise",
    "left hook. boxing",
    "lever lateral raise",
    "lever military press ",
    "lever one arm shoulder press ",
    "lever seated reverse fly",
    "lever seated reverse fly (parallel grip)",
    "lever seated shoulder press",
    "lever shoulder press ",
    "lever shoulder press  v. 2",
    "lever shoulder press  v. 3",
    "rear deltoid stretch",
    "resistance band seated shoulder press",
    "smith behind neck press",
    "smith rear delt row",
    "smith seated shoulder press",
    "smith shoulder press",
    "smith standing behind head military press",
    "smith standing military press",
    "smith upright row",
    "standing behind neck press",
    "weighted front raise",
    "weighted kneeling step with swing",
    "weighted round arm",
  ],
  "upper arms": [
    "assisted standing triceps extension (with towel)",
    "assisted triceps dip (kneeling)",
    "band alternating biceps curl",
    "band close-grip push-up",
    "band concentration curl",
    "band one arm overhead biceps curl",
    "band side triceps extension",
    "barbell alternate biceps curl",
    "barbell biceps curl (with arm blaster)",
    "barbell close-grip bench press",
    "barbell curl",
    "barbell decline close grip to skull press",
    "barbell drag curl",
    "barbell incline close grip bench press",
    "barbell incline reverse-grip press",
    "barbell jm bench press",
    "barbell lying back of the head tricep extension",
    "barbell lying close-grip press",
    "barbell lying close-grip triceps extension",
    "barbell lying extension",
    "barbell lying preacher curl",
    "barbell lying triceps extension",
    "barbell lying triceps extension skull crusher",
    "barbell one arm floor press",
    "barbell pin presses",
    "barbell preacher curl",
    "barbell prone incline curl",
    "barbell reverse close-grip bench press",
    "barbell reverse curl",
    "barbell reverse grip skullcrusher",
    "barbell reverse preacher curl",
    "barbell seated close grip behind neck triceps extension",
    "barbell seated close-grip concentration curl",
    "barbell seated overhead triceps extension",
    "barbell standing close grip curl",
    "barbell standing concentration curl",
    "barbell standing overhead triceps extension",
    "barbell standing reverse grip curl",
    "barbell standing wide grip biceps curl",
    "barbell standing wide-grip curl",
    "bench dip (knees bent)",
    "bench dip on floor",
    "biceps leg concentration curl",
    "biceps narrow pull-ups",
    "biceps pull-up",
    "body-up",
    "bodyweight kneeling triceps extension",
    "bodyweight side lying biceps curl",
    "cable alternate triceps extension",
    "cable close grip curl",
    "cable concentration curl",
    "cable concentration extension (on knee)",
    "cable curl",
    "cable drag curl",
    "cable hammer curl (with rope)",
    "cable high pulley overhead tricep extension",
    "cable incline triceps extension",
    "cable kickback",
    "cable kneeling triceps extension",
    "cable lying bicep curl",
    "cable lying close-grip curl",
    "cable lying triceps extension v. 2",
    "cable one arm curl",
    "cable one arm preacher curl",
    "cable one arm reverse preacher curl",
    "cable one arm tricep pushdown",
    "cable overhead curl",
    "cable overhead curl on exercise ball",
    "cable overhead triceps extension (rope attachment)",
    "cable preacher curl",
    "cable pulldown bicep curl",
    "cable pushdown",
    "cable pushdown (with rope attachment)",
    "cable rear drive",
    "cable reverse curl",
    "cable reverse grip triceps pushdown (sz-bar) (with arm blaster)",
    "cable reverse one arm curl",
    "cable reverse preacher curl",
    "cable reverse-grip pushdown",
    "cable rope hammer preacher curl",
    "cable rope high pulley overhead tricep extension",
    "cable rope incline tricep extension",
    "cable rope lying on floor tricep extension",
    "cable rope one arm hammer preacher curl",
    "cable seated curl",
    "cable seated one arm concentration curl",
    "cable seated overhead curl",
    "cable squatting curl",
    "cable standing inner curl",
    "cable standing one arm triceps extension",
    "cable standing pulldown (with rope)",
    "cable standing reverse grip one arm overhead tricep extension",
    "cable triceps pushdown (v-bar)",
    "cable triceps pushdown (v-bar) (with arm blaster)",
    "cable two arm curl on incline bench",
    "cable two arm tricep kickback",
    "close-grip push-up",
    "close-grip push-up (on knees)",
    "diamond push-up",
    "dumbbell alternate biceps curl",
    "dumbbell alternate biceps curl (with arm blaster)",
    "dumbbell alternate hammer preacher curl",
    "dumbbell alternate preacher curl",
    "dumbbell alternate seated hammer curl",
    "dumbbell alternating bicep curl with leg raised on exercise ball",
    "dumbbell alternating seated bicep curl on exercise ball",
    "dumbbell bicep curl lunge with bowling motion",
    "dumbbell bicep curl on exercise ball with leg raised",
    "dumbbell bicep curl with stork stance",
    "dumbbell biceps curl",
    "dumbbell biceps curl (with arm blaster)",
    "dumbbell biceps curl reverse",
    "dumbbell biceps curl squat",
    "dumbbell biceps curl v sit on bosu ball",
    "dumbbell close grip press",
    "dumbbell close-grip press",
    "dumbbell concentration curl",
    "dumbbell cross body hammer curl",
    "dumbbell cross body hammer curl v. 2",
    "dumbbell decline one arm hammer press",
    "dumbbell decline triceps extension",
    "dumbbell forward lunge triceps extension",
    "dumbbell hammer curl",
    "dumbbell hammer curl on exercise ball",
    "dumbbell hammer curl v. 2",
    "dumbbell hammer curls (with arm blaster)",
    "dumbbell high curl",
    "dumbbell incline biceps curl",
    "dumbbell incline curl",
    "dumbbell incline curl v. 2",
    "dumbbell incline hammer curl",
    "dumbbell incline hammer press on exercise ball",
    "dumbbell incline inner biceps curl",
    "dumbbell incline one arm hammer press",
    "dumbbell incline one arm hammer press on exercise ball",
    "dumbbell incline triceps extension",
    "dumbbell incline two arm extension",
    "dumbbell kickback",
    "dumbbell kickbacks on exercise ball",
    "dumbbell kneeling bicep curl exercise ball",
    "dumbbell lunge with bicep curl",
    "dumbbell lying  extension (across face)",
    "dumbbell lying alternate extension",
    "dumbbell lying elbow press",
    "dumbbell lying one arm pronated triceps extension",
    "dumbbell lying one arm supinated triceps extension",
    "dumbbell lying single extension",
    "dumbbell lying supine biceps curl",
    "dumbbell lying supine curl",
    "dumbbell lying triceps extension",
    "dumbbell lying wide curl",
    "dumbbell neutral grip bench press",
    "dumbbell one arm concetration curl (on stability ball)",
    "dumbbell one arm french press on exercise ball",
    "dumbbell one arm hammer preacher curl",
    "dumbbell one arm hammer press on exercise ball",
    "dumbbell one arm kickback",
    "dumbbell one arm prone curl",
    "dumbbell one arm prone hammer curl",
    "dumbbell one arm reverse preacher curl",
    "dumbbell one arm reverse spider curl",
    "dumbbell one arm seated bicep curl on exercise ball",
    "dumbbell one arm seated hammer curl",
    "dumbbell one arm standing curl",
    "dumbbell one arm standing hammer curl",
    "dumbbell one arm triceps extension (on bench)",
    "dumbbell one arm zottman preacher curl",
    "dumbbell over bench neutral wrist curl",
    "dumbbell over bench one arm  neutral wrist curl",
    "dumbbell palms in incline bench press",
    "dumbbell peacher hammer curl",
    "dumbbell preacher curl",
    "dumbbell preacher curl over exercise ball",
    "dumbbell pronate-grip triceps extension",
    "dumbbell prone incline curl",
    "dumbbell prone incline hammer curl",
    "dumbbell revers grip biceps curl",
    "dumbbell reverse preacher curl",
    "dumbbell reverse spider curl",
    "dumbbell seated alternate hammer curl on exercise ball",
    "dumbbell seated bench extension",
    "dumbbell seated bent over alternate kickback",
    "dumbbell seated bent over triceps extension",
    "dumbbell seated bicep curl",
    "dumbbell seated biceps curl (on stability ball)",
    "dumbbell seated biceps curl to shoulder press",
    "dumbbell seated curl",
    "dumbbell seated hammer curl",
    "dumbbell seated inner biceps curl",
    "dumbbell seated kickback",
    "dumbbell seated neutral wrist curl",
    "dumbbell seated one arm bicep curl on exercise ball with leg raised",
    "dumbbell seated one arm kickback",
    "dumbbell seated preacher curl",
    "dumbbell seated revers grip concentration curl",
    "dumbbell seated reverse grip one arm overhead tricep extension",
    "dumbbell seated triceps extension",
    "dumbbell standing alternate hammer curl and press",
    "dumbbell standing alternating tricep kickback",
    "dumbbell standing bent over one arm triceps extension",
    "dumbbell standing bent over two arm triceps extension",
    "dumbbell standing biceps curl",
    "dumbbell standing concentration curl",
    "dumbbell standing inner biceps curl v. 2",
    "dumbbell standing kickback",
    "dumbbell standing one arm concentration curl",
    "dumbbell standing one arm curl (over incline bench)",
    "dumbbell standing one arm curl over incline bench",
    "dumbbell standing one arm extension",
    "dumbbell standing one arm reverse curl",
    "dumbbell standing preacher curl",
    "dumbbell standing reverse curl",
    "dumbbell standing triceps extension",
    "dumbbell standing zottman preacher curl",
    "dumbbell step up single leg balance with bicep curl",
    "dumbbell tate press",
    "dumbbell tricep kickback with stork stance",
    "dumbbell twisting bench press",
    "dumbbell waiter biceps curl",
    "dumbbell zottman curl",
    "dumbbell zottman preacher curl",
    "dumbbells seated triceps extension",
    "elbow dips",
    "exercise ball dip",
    "exercise ball seated triceps stretch",
    "exercise ball supine triceps extension",
    "ez bar french press on exercise ball",
    "ez bar lying close grip triceps extension behind head",
    "ez bar seated close grip concentration curl",
    "ez bar standing french press",
    "ez barbell close grip preacher curl",
    "ez barbell close-grip curl",
    "ez barbell curl",
    "ez barbell decline close grip face press",
    "ez barbell decline triceps extension",
    "ez barbell incline triceps extension",
    "ez barbell jm bench press",
    "ez barbell reverse grip curl",
    "ez barbell reverse grip preacher curl",
    "ez barbell seated curls",
    "ez barbell seated triceps extension",
    "ez barbell spider curl",
    "ez-bar biceps curl (with arm blaster)",
    "ez-bar close-grip bench press",
    "ez-barbell standing wide grip biceps curl",
    "handstand",
    "handstand push-up",
    "impossible dips",
    "incline close-grip push-up",
    "kettlebell bottoms up clean from the hang position",
    "kettlebell double alternating hang clean",
    "lever bicep curl",
    "lever hammer grip preacher curl",
    "lever overhand triceps dip",
    "lever preacher curl",
  ],
  "upper legs": [
    "all fours squad stretch",
    "arms apart circular toe touch (male)",
    "assisted lying glutes stretch",
    "assisted lying gluteus and piriformis stretch",
    "assisted prone hamstring",
    "assisted prone lying quads stretch",
    "assisted side lying adductor stretch",
    "backward jump",
    "balance board",
    "band bent-over hip extension",
    "band hip lift",
    "band lying hip internal rotation",
    "band one arm single leg split squat",
    "band pull through",
    "band seated hip internal rotation",
    "band single leg split squat",
    "band squat",
    "band squat row",
    "band step-up",
    "band stiff leg deadlift",
    "band straight back stiff leg deadlift",
    "barbell bench front squat",
    "barbell bench squat",
    "barbell clean and press",
    "barbell clean-grip front squat",
    "barbell deadlift",
    "barbell front chest squat",
    "barbell front squat",
    "barbell full squat",
    "barbell full squat (back pov)",
    "barbell full squat (side pov)",
    "barbell full zercher squat",
    "barbell glute bridge",
    "barbell glute bridge two legs on bench (male)",
    "barbell good morning",
    "barbell hack squat",
    "barbell high bar squat",
    "barbell jefferson squat",
    "barbell jump squat",
    "barbell lateral lunge",
    "barbell low bar squat",
    "barbell lunge",
    "barbell lying lifting (on hip)",
    "barbell narrow stance squat",
    "barbell one arm side deadlift",
    "barbell one leg squat",
    "barbell overhead squat",
    "barbell rack pull",
    "barbell rear lunge",
    "barbell rear lunge v. 2",
    "barbell romanian deadlift",
    "barbell seated good morning",
    "barbell side split squat",
    "barbell side split squat v. 2",
    "barbell single leg deadlift",
    "barbell single leg split squat",
    "barbell speed squat",
    "barbell split squat v. 2",
    "barbell squat (on knees)",
    "barbell squat jump step rear lunge",
    "barbell step-up",
    "barbell stiff leg good morning",
    "barbell straight leg deadlift",
    "barbell sumo deadlift",
    "barbell wide squat",
    "barbell zercher squat",
    "basic toe touch (male)",
    "bench hip extension",
    "bent knee lying twist (male)",
    "bodyweight drop jump squat",
    "butterfly yoga pose",
    "cable assisted inverse leg curl",
    "cable deadlift",
    "cable hip adduction",
    "cable pull through (with rope)",
    "cable standing hip extension",
    "chair leg extended stretch",
    "curtsey squat",
    "dumbbell bench squat",
    "dumbbell clean",
    "dumbbell contralateral forward lunge",
    "dumbbell deadlift",
    "dumbbell goblet squat",
    "dumbbell lunge",
    "dumbbell lying femoral",
    "dumbbell one arm snatch",
    "dumbbell plyo squat",
    "dumbbell rear lunge",
    "dumbbell romanian deadlift",
    "dumbbell single leg deadlift",
    "dumbbell single leg deadlift with stepbox support",
    "dumbbell single leg split squat",
    "dumbbell single leg squat",
    "dumbbell squat",
    "dumbbell step-up",
    "dumbbell step-up lunge",
    "dumbbell step-up split squat",
    "dumbbell stiff leg deadlift",
    "dumbbell straight leg deadlift",
    "dumbbell sumo pull through",
    "dumbbell supported squat",
    "exercise ball hip flexor stretch",
    "exercise ball one leg prone lower body rotation",
    "exercise ball one legged diagonal kick hamstring curl",
    "exercise ball seated hamstring stretch",
    "farmers walk",
    "flutter kicks",
    "forward jump",
    "forward lunge (male)",
    "frankenstein squat",
    "glute bridge march",
    "glute bridge two legs on bench (male)",
    "glute-ham raise",
    "hamstring stretch",
    "hands clasped circular toe touch (male)",
    "hands reversed clasped circular toe touch (male)",
    "hug keens to chest",
    "intermediate hip flexor and quad stretch",
    "inverse leg curl (bench support)",
    "inverse leg curl (on pull-up cable machine)",
    "iron cross stretch",
    "jump squat",
    "jump squat v. 2",
    "kettlebell front squat",
    "kettlebell goblet squat",
    "kettlebell hang clean",
    "kettlebell lunge pass through",
    "kettlebell pistol squat",
    "kettlebell swing",
    "kettlebell turkish get up (squat style)",
    "kick out sit",
    "kneeling jump squat",
    "leg up hamstring stretch",
    "lever alternate leg press ",
    "lever deadlift ",
    "lever hip extension v. 2",
    "lever horizontal one leg press",
    "lever kneeling leg curl ",
    "lever leg extension",
    "lever lying leg curl",
    "lever lying two-one leg curl",
    "lever reverse hyperextension ",
    "lever seated good morning",
    "lever seated hip abduction",
    "lever seated hip adduction",
    "lever seated leg curl",
    "low glute bridge on floor",
    "lunge with jump",
    "lying (side) quads stretch",
    "march sit (wall)",
    "monster walk",
    "one leg squat",
    "outside leg kick push-up",
    "pelvic tilt into bridge",
    "pike-to-cobra push-up",
    "potty squat with support",
    "power clean",
    "push-up inside leg kick",
    "quads",
    "quick feet v. 2",
    "rear decline bridge",
    "reclining big toe pose with rope",
    "resistance band hip thrusts on knees (female)",
    "resistance band leg extension",
    "resistance band seated hip abduction",
    "reverse hyper extension (on stability ball)",
    "reverse hyper on flat bench",
    "rocking frog stretch",
    "roller hip lat stretch",
    "roller hip stretch",
    "runners stretch",
    "seated glute stretch",
    "seated piriformis stretch",
    "seated wide angle pose sequence",
    "self assisted inverse leg curl",
    "self assisted inverse leg curl (on floor)",
    "side bridge hip abduction",
    "side hip abduction",
    "side lying hip adduction (male)",
    "side plank hip adduction",
    "single leg bridge with outstretched leg",
    "single leg platform slide",
    "single leg squat (pistol) male",
    "sissy squat",
    "sled 45 degrees one leg press",
    "sled 45в° leg press",
    "sled 45в° leg press (back pov)",
    "sled 45в° leg press (side pov)",
    "sled 45в° leg wide press",
    "sled closer hack squat",
    "sled hack squat",
    "sled lying squat",
    "smith bent knee good morning",
    "smith chair squat",
    "smith deadlift",
    "smith front squat (clean grip)",
    "smith full squat",
    "smith hack squat",
    "smith leg press",
    "smith low bar squat",
    "smith single leg split squat",
    "smith sprint lunge",
    "smith squat",
    "smith sumo squat",
    "snatch pull",
    "spider crawl push up",
    "split squats",
    "squat jerk",
    "squat on bosu ball",
    "squat to overhead reach",
    "squat to overhead reach with twist",
    "standing hamstring and calf stretch with strap",
    "standing single leg curl",
    "straight leg outer hip abductor",
    "suspended split squat",
    "swimmer kicks v. 2 (male)",
    "tire flip",
    "trap bar deadlift",
    "twist hip lift",
    "walking lunge",
    "weighted cossack squats (male)",
    "weighted lunge with swing",
    "weighted sissy squat",
    "weighted squat",
    "weighted stretch lunge",
    "world greatest stretch",
  ],
  waist: [
    "3/4 sit-up",
    "45° side bend",
    "air bike",
    "alternate heel touchers",
    "arm slingers hanging bent knee legs",
    "arm slingers hanging straight legs",
    "arms overhead full sit-up (male)",
    "assisted hanging knee raise",
    "assisted hanging knee raise with throw down",
    "assisted lying leg raise with lateral throw down",
    "assisted lying leg raise with throw down",
    "assisted motion russian twist",
    "assisted prone rectus femoris stretch",
    "assisted sit-up",
    "band alternating v-up",
    "band assisted wheel rollerout",
    "band bicycle crunch",
    "band horizontal pallof press",
    "band jack knife sit-up",
    "band kneeling twisting crunch",
    "band lying straight leg raise",
    "band push sit-up",
    "band seated twist",
    "band standing crunch",
    "band standing twisting crunch",
    "band v-up",
    "band vertical pallof press",
    "barbell press sit-up",
    "barbell rollerout",
    "barbell rollerout from bench",
    "barbell seated twist",
    "barbell side bent v. 2",
    "barbell sitted alternate leg raise",
    "barbell sitted alternate leg raise (female)",
    "barbell standing ab rollerout",
    "barbell standing twist",
    "bodyweight incline side plank",
    "bottoms-up",
    "bridge - mountain climber (cross body)",
    "butt-ups",
    "cable judo flip",
    "cable kneeling crunch",
    "cable reverse crunch",
    "cable russian twists (on stability ball)",
    "cable seated crunch",
    "cable seated twist",
    "cable side bend",
    "cable side bend crunch (bosu ball)",
    "cable side crunch",
    "cable standing crunch",
    "cable standing crunch (with rope attachment)",
    "cable standing lift",
    "cable tuck reverse crunch",
    "cable twist",
    "cable twist (up-down)",
    "captains chair straight leg raise",
    "cocoons",
    "crab twist toe touch",
    "cross body crunch",
    "crunch (hands overhead)",
    "crunch (on stability ball)",
    "crunch (on stability ball, arms straight)",
    "crunch floor",
    "curl-up",
    "dead bug",
    "decline crunch",
    "decline sit-up",
    "dumbbell side bend",
    "elbow-to-knee",
    "flag",
    "flexion leg sit up (bent knee)",
    "flexion leg sit up (straight arm)",
    "frog crunch",
    "frog planche",
    "front lever",
    "front plank with twist",
    "full maltese",
    "full planche",
    "gorilla chin",
    "groin crunch",
    "half sit-up (male)",
    "hanging leg hip raise",
    "hanging leg raise",
    "hanging oblique knee raise",
    "hanging pike",
    "hanging straight leg hip raise",
    "hanging straight leg raise",
    "hanging straight twisting leg hip raise",
    "hip raise (bent knee)",
    "inchworm",
    "inchworm v. 2",
    "incline leg hip raise (leg straight)",
    "incline twisting sit-up",
    "jackknife sit-up",
    "janda sit-up",
    "kettlebell advanced windmill",
    "kettlebell bent press",
    "kettlebell double windmill",
    "kettlebell figure 8",
    "kettlebell windmill",
    "knee touch crunch",
    "kneeling plank tap shoulder (male)",
    "l-sit on floor",
    "landmine 180",
    "lean planche",
    "leg pull in flat bench",
    "lever kneeling twist",
    "lever seated crunch",
    "lever seated crunch (chest pad)",
    "lever seated crunch v. 2",
    "lever seated leg raise crunch ",
    "lever seated twist",
    "lunge with twist",
    "lying elbow to knee",
    "lying leg raise flat bench",
    "lying leg-hip raise",
    "negative crunch",
    "oblique crunch v. 2",
    "oblique crunches floor",
    "one arm slam (with medicine ball)",
    "otis up",
    "pelvic tilt",
    "posterior step to overhead reach",
    "potty squat",
    "power point plank",
    "prisoner half sit-up (male)",
    "prone twist on stability ball",
    "pull-in (on stability ball)",
    "push-up to side plank",
    "quarter sit-up",
    "reverse crunch",
    "reverse plank with leg lift",
    "roller body saw",
    "roller reverse crunch",
    "russian twist",
    "seated leg raise",
    "seated side crunch (wall)",
    "shoulder tap",
    "side bridge v. 2",
    "side hip (on parallel bars)",
    "side-to-side toe touch (male)",
    "sit-up v. 2",
    "sit-up with arms on chest",
    "sledge hammer",
    "smith hip raise",
    "spell caster",
    "spine twist",
    "stability ball crunch (full range hands behind head)",
    "standing wheel rollerout",
    "straddle maltese",
    "straddle planche",
    "suspended abdominal fallout",
    "suspended reverse crunch",
    "tuck crunch",
    "twisted leg raise",
    "twisted leg raise (female)",
    "v-sit on floor",
    "vertical leg raise (on parallel bars)",
    "weighted crunch",
    "weighted decline sit-up",
    "weighted front plank",
    "weighted hanging leg-hip raise",
    "weighted overhead crunch (on stability ball)",
    "weighted russian twist",
    "weighted russian twist (legs up)",
    "weighted russian twist v. 2",
    "weighted seated twist (on stability ball)",
    "weighted side bend (on stability ball)",
    "wheel rollerout",
    "wind sprints",
  ],
};
